first html layout
marzieh67/ReDI_Frontend_FinalProject pull request #2
Opened 2020-09-26 23:49 UTC by marzieh67

2020-09-28 20:24 UTC, MrTim commented
Hi @marzieh67  could you maybe add a short description what this layout is for? Because it's hard to guess based only on the code :)

2020-10-03 15:59 UTC, MrTim requested changes
Good start. Left some comments, please clean up them and we'll check again.

2020-10-03 15:59 UTC, MrTim commented on index.html
> +
You don't need these empty lines

2020-10-03 15:59 UTC, MrTim commented on index.html
> +    <div class="search contain">
you're using classes but there is no CSS file linked to this file. Please next time create all styles and link them here.

2020-10-03 15:59 UTC, MrTim commented on index.html
> +
this empty line is not needed as well

2020-10-03 15:59 UTC, MrTim commented on index.html
> +
empty lines)

2020-10-03 15:59 UTC, MrTim commented on index.html
> +<!--Should be done:
This section and empty lines as separators you don't need. When you get to the point when it's needed then you will add this section.

2020-10-03 20:18 UTC, marzieh67 commented on index.html
> +<!--Should be done:
@MrTim Thank you Tim , I deleted the extra lines.

2020-10-04 12:50 UTC, MrTim approved these changes
Cool! Now you're good to go in merging this pr to master.

2020-10-04 17:18 UTC, merged